import datetime
x = datetime.datetime.now()
print("Current Date & Time  : ",x)
print("Year   :",x.year)
print("Month  :",x.month)
print("Day    :",x.day)
print("Hour           :",x.hour)
print("Minute         :",x.minute)
print("Second         :",x.second)
print("Micro-Second   :",x.microsecond)
