def employee(id, name, place, company, salary):
    print("___Employee Details___")
    print("Employee ID    :",id)
    print("Employee Name  :",name)
    print("Place          :",place)
    print("Company        : ",company)
    print("Salary         : ",salary)
employee(123,"Rahul","Kochi","TCS",25000)
employee(6580,"Vishnu","Pala","UST","30000")
employee(8547,"Kannan","Palluruthy","DTDC","85000")